feat: fix bug where repo translations would be saved in {owner}/{repo} subdirectory instead of {repo}

diff --git a/.github/workflows/extract-translation-source-files.yml b/.github/workflows/extract-translation-source-files.yml
--- a/.github/workflows/extract-translation-source-files.yml
+++ b/.github/workflows/extract-translation-source-files.yml
@@ -34,91 +34,91 @@ jobs:
             const selectedRepo = ${{ toJSON(github.event.inputs.repo) }} ?? '';
 
             const allPythonRepos = [
-              'edx/AudioXBlock',
-              'edx/DoneXBlock',
-              'openedx/FeedbackXBlock',
-              'edx/RecommenderXBlock',
-              'edx/ai-translations',
-              'edx/commerce-coordinator',
-              'edx/course-discovery',
-              'edx/credentials',
-              'edx/credentials-themes',
-              'edx/edx-ace',
-              'edx/edx-exams',
-              'edx/edx-platform',
-              'edx/portal-designer',
-              'edx/registrar',
-              'edx/enterprise-access',
-              'edx/enterprise-catalog',
-              'edx/enterprise-subsidy',
-              'edx/financial-assistance',
-              'edx/order-fulfillment',
-              'edx/sanctions',
-              'edx/video-encode-manager',
-              'openedx/edx-bulk-grades',
-              'openedx/edx-ora2',
-              'edx/edx-proctoring',
-              'edx/platform-plugin-aspects',
-              'openedx/xblock-drag-and-drop-v2',
-              'edx/xblock-free-text-response',
-              'openedx/xblock-google-drive',
-              'openedx/xblock-image-explorer',
-              'edx/xblock-image-modal',
-              'edx/xblock-lti-consumer',
-              'edx/xblock-qualtrics-survey',
-              'edx/xblock-sql-grader',
-              'edx/xblock-submit-and-compare',
+              { owner: 'edx', repo: 'AudioXBlock' },
+              { owner: 'edx', repo: 'DoneXBlock' },
+              { owner: 'openedx', repo: 'FeedbackXBlock' },
+              { owner: 'edx', repo: 'RecommenderXBlock' },
+              { owner: 'edx', repo: 'ai-translations' },
+              { owner: 'edx', repo: 'commerce-coordinator' },
+              { owner: 'edx', repo: 'course-discovery' },
+              { owner: 'edx', repo: 'credentials' },
+              { owner: 'edx', repo: 'credentials-themes' },
+              { owner: 'edx', repo: 'edx-ace' },
+              { owner: 'edx', repo: 'edx-exams' },
+              { owner: 'edx', repo: 'edx-platform' },
+              { owner: 'edx', repo: 'portal-designer' },
+              { owner: 'edx', repo: 'registrar' },
+              { owner: 'edx', repo: 'enterprise-access' },
+              { owner: 'edx', repo: 'enterprise-catalog' },
+              { owner: 'edx', repo: 'enterprise-subsidy' },
+              { owner: 'edx', repo: 'financial-assistance' },
+              { owner: 'edx', repo: 'order-fulfillment' },
+              { owner: 'edx', repo: 'sanctions' },
+              { owner: 'edx', repo: 'video-encode-manager' },
+              { owner: 'openedx', repo: 'edx-bulk-grades' },
+              { owner: 'openedx', repo: 'edx-ora2' },
+              { owner: 'edx', repo: 'edx-proctoring' },
+              { owner: 'edx', repo: 'platform-plugin-aspects' },
+              { owner: 'openedx', repo: 'xblock-drag-and-drop-v2' },
+              { owner: 'edx', repo: 'xblock-free-text-response' },
+              { owner: 'openedx', repo: 'xblock-google-drive' },
+              { owner: 'openedx', repo: 'xblock-image-explorer' },
+              { owner: 'edx', repo: 'xblock-image-modal' },
+              { owner: 'edx', repo: 'xblock-lti-consumer' },
+              { owner: 'edx', repo: 'xblock-qualtrics-survey' },
+              { owner: 'edx', repo: 'xblock-sql-grader' },
+              { owner: 'edx', repo: 'xblock-submit-and-compare' },
             ];
 
             const allJavascriptRepos = [
-              'edx/frontend-app-account',
-              'edx/frontend-app-admin-portal',
-              'edx/frontend-app-authn',
-              'edx/frontend-app-authoring',
-              'edx/frontend-app-communications',
-              'edx/frontend-app-discussions',
-              'edx/frontend-app-enterprise-api-doc',
-              'edx/frontend-app-enterprise-checkout',
-              'edx/frontend-app-enterprise-public-catalog',
-              'edx/frontend-app-gradebook',
-              'edx/frontend-app-learner-dashboard',
-              'edx/frontend-app-learner-portal-enterprise',
-              'edx/frontend-app-learner-portal-programs',
-              'edx/frontend-app-learner-record',
-              'edx/frontend-app-learning',
-              'edx/frontend-app-ora',
-              'edx/frontend-app-ora-grading',
-              'edx/frontend-app-payment',
-              'edx/frontend-app-profile',
-              'edx/frontend-app-program-console',
-              'edx/frontend-app-publisher',
-              'edx/frontend-app-skills',
-              'edx/frontend-app-support-tools',
-              'edx/frontend-component-authn-edx',
-              'edx/frontend-component-footer-edx',
-              'edx/frontend-component-header-edx',
-              'edx/frontend-components-tinymce-advanced-plugins-edx',
-              'edx/frontend-plugin-advertisements',
-              'edx/frontend-plugin-authn',
-              'edx/frontend-plugin-learner-dashboard',
-              'edx/frontend-plugin-notifications',
-              'edx/frontend-plugin-persona',
-              'edx/frontend-plugin-recommendations',
-              'edx/frontend-platform',
-              'openedx/paragon',
-              'edx/studio-frontend',
-              'openedx/frontend-plugin-framework',
+              { owner: 'edx', repo: 'frontend-app-account' },
+              { owner: 'edx', repo: 'frontend-app-admin-portal' },
+              { owner: 'edx', repo: 'frontend-app-authn' },
+              { owner: 'edx', repo: 'frontend-app-authoring' },
+              { owner: 'edx', repo: 'frontend-app-communications' },
+              { owner: 'edx', repo: 'frontend-app-discussions' },
+              { owner: 'edx', repo: 'frontend-app-enterprise-api-doc' },
+              { owner: 'edx', repo: 'frontend-app-enterprise-checkout' },
+              { owner: 'edx', repo: 'frontend-app-enterprise-public-catalog' },
+              { owner: 'edx', repo: 'frontend-app-gradebook' },
+              { owner: 'edx', repo: 'frontend-app-learner-dashboard' },
+              { owner: 'edx', repo: 'frontend-app-learner-portal-enterprise' },
+              { owner: 'edx', repo: 'frontend-app-learner-portal-programs' },
+              { owner: 'edx', repo: 'frontend-app-learner-record' },
+              { owner: 'edx', repo: 'frontend-app-learning' },
+              { owner: 'edx', repo: 'frontend-app-ora' },
+              { owner: 'edx', repo: 'frontend-app-ora-grading' },
+              { owner: 'edx', repo: 'frontend-app-payment' },
+              { owner: 'edx', repo: 'frontend-app-profile' },
+              { owner: 'edx', repo: 'frontend-app-program-console' },
+              { owner: 'edx', repo: 'frontend-app-publisher' },
+              { owner: 'edx', repo: 'frontend-app-skills' },
+              { owner: 'edx', repo: 'frontend-app-support-tools' },
+              { owner: 'edx', repo: 'frontend-component-authn-edx' },
+              { owner: 'edx', repo: 'frontend-component-footer-edx' },
+              { owner: 'edx', repo: 'frontend-component-header-edx' },
+              { owner: 'edx', repo: 'frontend-components-tinymce-advanced-plugins-edx' },
+              { owner: 'edx', repo: 'frontend-plugin-advertisements' },
+              { owner: 'edx', repo: 'frontend-plugin-authn' },
+              { owner: 'edx', repo: 'frontend-plugin-learner-dashboard' },
+              { owner: 'edx', repo: 'frontend-plugin-notifications' },
+              { owner: 'edx', repo: 'frontend-plugin-persona' },
+              { owner: 'edx', repo: 'frontend-plugin-recommendations' },
+              { owner: 'edx', repo: 'frontend-platform' },
+              { owner: 'openedx', repo: 'paragon' },
+              { owner: 'edx', repo: 'studio-frontend' },
+              { owner: 'openedx', repo: 'frontend-plugin-framework' },
             ];
 
-            const javascriptReposWithSubpackages = [
-              'edx/frontend-plugins/cohesion-wrapper',
-              'edx/frontend-plugins/course-app-translation-plugin',
-              'edx/frontend-plugins/course-end-enterprise-plugins',
-              'edx/frontend-plugins/course-outline-sidebar-trigger-plugin',
-              'edx/frontend-plugins/left-sidebar-navigation-plugin',
-              'edx/frontend-plugins/progress-tab-grade-plugins',
-              'edx/frontend-plugins/unit-title-plugin',
-            ];
+            # const javascriptReposWithSubpackages = [
+            #   { owner: 'edx', repo: 'frontend-plugins/cohesion-wrapper' },
+            #   { owner: 'edx', repo: 'frontend-plugins/course-app-translation-plugin' },
+            #   { owner: 'edx', repo: 'frontend-plugins/course-end-enterprise-plugins' },
+            #   { owner: 'edx', repo: 'frontend-plugins/course-outline-sidebar-trigger-plugin' },
+            #   { owner: 'edx', repo: 'frontend-plugins/left-sidebar-navigation-plugin' },
+            #   { owner: 'edx', repo: 'frontend-plugins/progress-tab-grade-plugins' },
+            #   { owner: 'edx', repo: 'frontend-plugins/unit-title-plugin' },
+            # ];
 
             // When https://2u-internal.atlassian.net/wiki/spaces/AU/pages/2786066453/Mobile+app+translations
             // tasks or equivalents are completed, uncomment and correct this section.
@@ -220,7 +220,7 @@ jobs:
       # using max-parallel to avoid git push/pull issues when running in parallel
       max-parallel: 1
       matrix:
-        repo: ${{ fromJson(needs.setup-matrix.outputs.python_repos) }}
+        repo_config: ${{ fromJson(needs.setup-matrix.outputs.python_repos) }}
 
     runs-on: ubuntu-latest
     continue-on-error: true
@@ -246,22 +246,22 @@ jobs:
           ref: ${{ needs.setup-branch.outputs.branch }}
 
       # Clones the app repository
-      - name: clone ${{ matrix.repo }}
+      - name: clone ${{ matrix.repo_config.owner }}/${{ matrix.repo_config.repo }}
         uses: actions/checkout@v5
         with:
-          repository: ${{ matrix.repo }}
+          repository: ${{ matrix.repo_config.owner }}/${{ matrix.repo_config.repo }}
           ref: ${{ github.event.inputs.ref }}
-          path: translations/${{ matrix.repo }}
+          path: translations/${{ matrix.repo_config.repo }}
           token: ${{ steps.generate_token.outputs.token }}
 
       - name: prepare the environment with edx-platform specific changes
-        if: matrix.repo == 'edx-platform'
+        if: matrix.repo_config.repo == 'edx-platform'
         run: |
           # This is needed for edx-platform base.txt packages
           sudo apt install -y libxml2-dev libxmlsec1-dev libxslt1-dev
 
           # There is a theme directory with it's own conf/locale directory, we need to remove that
-          rm -rf translations/${{ matrix.repo }}/themes/conf
+          rm -rf translations/${{ matrix.repo_config.repo }}/themes/conf
 
       # Setup Python
       - name: setup python
@@ -287,25 +287,34 @@ jobs:
             # Install edx-platform specific apps (e.g. wiki) which is required to extract translations from
             pip install -r $EDX_BASE_REQS
           fi
-          
-          # Common requirement app file patterns to try
-          APP_BASE="translations/${{ matrix.repo }}"
+
+          APP_BASE="translations/${{ matrix.repo_config.repo }}"
           REQ_FILES=(
             "$APP_BASE/requirements/base.txt"
           )
-          
-          for req_file in "${REQ_FILES[@]}"; do
-            if test -f "$req_file"; then
-              echo "Installing $req_file for ${{ matrix.repo }}"
-              pip install -r "$req_file" || echo "Failed to install $req_file, continuing..."
-              break
-            fi
-          done
+  
+          # Avoid reinstall edx-platform requirements.
+          if [[ "${{ matrix.repo_config.repo }}" != "edx-platform" ]]; then
+            APP_BASE="translations/${{ matrix.repo_config.repo }}"
+
+            # Common requirement app file patterns to try to install from
+            REQ_FILES=(
+              "$APP_BASE/requirements/base.txt"
+            )
+
+            for req_file in "${REQ_FILES[@]}"; do
+              if test -f "$req_file"; then
+                echo "Installing $req_file for ${{ matrix.repo_config.repo }}"
+                pip install -r "$req_file" || echo "Failed to install $req_file, continuing..."
+                break
+              fi
+            done
+          fi
 
       # Extracts the translation source files
       - name: extract translation source files
         run: |
-          cd translations/${{ matrix.repo }}
+          cd translations/${{ matrix.repo_config.repo }}
           make extract_translations
         env:
           IS_OPENEDX_TRANSLATIONS_WORKFLOW: yes
@@ -313,7 +322,7 @@ jobs:
       # Validate compilation of translation source files
       - name: validate compilation of translation source files
         run: |
-          cd translations/${{ matrix.repo }}
+          cd translations/${{ matrix.repo_config.repo }}
           django-admin compilemessages --locale en
 
       # Preparations so git adds only the translation source files, found in conf/locale/en
@@ -324,8 +333,8 @@ jobs:
         run: |
           git config --global user.name "edx-translations-app"
           git config --global user.email "edx-translations-app@users.noreply.github.com"
-          # Change directory to translations/${{ matrix.repo }}
-          cd translations/${{ matrix.repo }}
+          # Change directory to translations/${{ matrix.repo_config.repo }}
+          cd translations/${{ matrix.repo_config.repo }}
           # finds the directory containing the english locale usually located in
           # */*/conf/locale/en
           # but also exclude any hidden directories that might exist for some reason
@@ -334,15 +343,15 @@ jobs:
           # If the repo complies with OEP-58, then we'll find only one directory that matches the above criteria
           # Otherwise, we'll consider it an error
           if [ $en_dir_count -gt 1 ]; then
-            echo "Error: More than one English locale directory found for ${{ matrix.repo }}!"
+            echo "Error: More than one English locale directory found for ${{ matrix.repo_config.repo }}!"
             exit 1
           elif [ $en_dir_count -eq 0 ]; then
-            echo "Error: Missing English locale directory for ${{ matrix.repo }}!"
+            echo "Error: Missing English locale directory for ${{ matrix.repo_config.repo }}!"
             exit 1
           fi
           # Save EN_DIR value to be used in next steps
           echo "EN_DIR=$EN_DIR" >> $GITHUB_ENV
-          # remove translations/${{ matrix.repo }}/.git so we don't commit a submodule
+          # remove translations/${{ matrix.repo_config.repo }}/.git so we don't commit a submodule
           rm -rf .git
 
       - name: add repo translation source files openedx-translations
@@ -351,7 +360,7 @@ jobs:
         run: |
           # finds the django.po and djangojs.po files generated by make
           # extract_translations into EN_DIR and adds them
-          cd translations/${{ matrix.repo }}
+          cd translations/${{ matrix.repo_config.repo }}
           DJANGO_PATH=$(find $EN_DIR -name 'django.po')
           DJANGOJS_PATH=$(find $EN_DIR -name 'djangojs.po')
           ############## Special support for XBlocks
@@ -380,7 +389,7 @@ jobs:
         if: "${{ env.GIT_STATUS > 0 }}"
         run: |
           # commit the changes
-          git commit -m "chore: add extracted translation source files from ${{ matrix.repo }}"
+          git commit -m "chore: add extracted translation source files from ${{ matrix.repo_config.repo }}"
           # push changes to branch
           git push
 
@@ -398,7 +407,7 @@ jobs:
         # * frontend-app-programs-dashboard
         # repos with errors running extract_translations
         # * frontend-template-application
-        repo: ${{ fromJson(needs.setup-matrix.outputs.js_repos) }}
+        repo_config: ${{ fromJson(needs.setup-matrix.outputs.js_repos) }}
     runs-on: ubuntu-latest
     continue-on-error: true
 
@@ -419,12 +428,12 @@ jobs:
           ref: ${{ needs.setup-branch.outputs.branch }}
 
       # Clones the app repository
-      - name: clone ${{ matrix.repo }}
+      - name: clone ${{ matrix.repo_config.repo }}
         uses: actions/checkout@v5
         with:
           repository: ${{ matrix.repo }}
           ref: ${{ github.event.inputs.ref }}
-          path: translations/${{ matrix.repo }}
+          path: translations/${{ matrix.repo_config.repo }}
           token: ${{ steps.generate_token.outputs.token }}
 
       # Sets up node/npm
@@ -436,7 +445,7 @@ jobs:
       # Extracts the translation source files
       - name: extract translation source files
         run: |
-          cd translations/${{ matrix.repo }}
+          cd translations/${{ matrix.repo_config.repo }}
           make extract_translations
 
       # git adds only the translation source files, found in src/i18n/transifex_input.json
@@ -448,9 +457,9 @@ jobs:
           # set identity
           git config --global user.name "edx-translations-app"
           git config --global user.email "edx-translations-app@users.noreply.github.com"
-          # Change directory to translations/${{ matrix.repo }}
-          cd translations/${{ matrix.repo }}
-          # remove translations/${{ matrix.repo }}/.git so we don't commit a submodule
+          # Change directory to translations/${{ matrix.repo_config.repo }}
+          cd translations/${{ matrix.repo_config.repo }}
+          # remove translations/${{ matrix.repo_config.repo }}/.git so we don't commit a submodule
           rm -rf .git
           # find transifex_input.json
           TRANSIFEX_JSON_PATH=$(find . -name 'transifex_input.json')
@@ -466,7 +475,7 @@ jobs:
         if: "${{ env.GIT_STATUS > 0 }}"
         run: |
           # commit the changes
-          git commit -m "chore: add extracted translation source files from ${{ matrix.repo }}"
+          git commit -m "chore: add extracted translation source files from ${{ matrix.repo_config.repo }}"
           # push changes to branch
           git push
 
