feat: add request to fetch JWT token and some other fixes

diff --git a/.github/workflows/seed-translations.yml b/.github/workflows/seed-translations.yml
--- a/.github/workflows/seed-translations.yml
+++ b/.github/workflows/seed-translations.yml
@@ -122,11 +122,11 @@ jobs:
             const selectedLanguage = languageInput ? languageInput.toLowerCase() : '';
 
             if (selectedApp !== '' && !allJavascriptApps.includes(selectedApp)) {
-              core.setFailed(`Selected application ${selectedApp} is not a valid option.`);
+              core.setFailed(`Selected application "${selectedApp}" is not a valid option.`);
               return;
             }
             if (selectedLanguage !== '' && !Object.keys(languageMap).includes(selectedLanguage)) {
-              core.setFailed(`Selected language ${selectedLanguage} is not a valid option.`);
+              core.setFailed(`Selected language "${selectedLanguage}" is not a valid option.`);
               return;
             }
 
@@ -148,8 +148,47 @@ jobs:
       - name: Clone repository
         uses: actions/checkout@v5
 
+      - name: Fetch LMS JWT token
+        id: fetch-jwt-token
+        run: |
+          response_file="/tmp/lms_token_response.json"
+
+          curl_exit_code=0
+          status_code=$(curl -sS --connect-timeout 10 --max-time 120 \
+            -w "%{http_code}" \
+            -o "$response_file" \
+            -X POST "${{ vars.LMS_ACCESS_TOKEN_URL }}" \
+            -d "grant_type=client_credentials" \
+            -d "client_id=${{ secrets.EDX_TRANSLATIONS_STAGE_CLIENT_ID }}" \
+            -d "client_secret=${{ secrets.EDX_TRANSLATIONS_STAGE_CLIENT_SECRET }}" \
+            -d "token_type=jwt") || curl_exit_code=$?
+
+          if [ "$curl_exit_code" -ne 0 ]; then
+            echo "Curl request to fetch LMS JWT failed with exit code $curl_exit_code."
+            exit 1
+          fi
+
+          if [ "$status_code" -ne 200 ]; then
+            echo "API call to fetch LMS JWT for application ${{ matrix.application }} with status code $status_code."
+            exit 1
+          fi
+
+          jwt_token=$(jq -r '.access_token' "$response_file")
+
+          if [ -z "$jwt_token" ] || [ "$jwt_token" = "null" ]; then
+            echo "Failed to extract access_token from LMS JWT response."
+            exit 1
+          fi
+
+          # Mask the JWT so as not to inadvertently expose it.
+          echo "::add-mask::$jwt_token"
+          echo "JWT_TOKEN=$jwt_token" >> $GITHUB_ENV
+
       - name: Seed translation languages for ${{ matrix.application }}
         run: |
+          # Mask the JWT so as not to inadvertently expose it.
+          echo "::add-mask::$JWT_TOKEN"
+
           translation_languages='${{ needs.setup.outputs.translation_languages }}'
 
           for lang in $(echo "$translation_languages" | jq -c '.[]'); do
@@ -172,23 +211,28 @@ jobs:
             fi
 
             curl_exit_code=0
-            status_code=$(curl -sS --connect-timeout 10 --max-time 60 -w "%{http_code}" -o /tmp/seed_translations_response.txt -X POST ${{ secrets.EDX_AI_TRANSLATIONS_API_ROOT }} \
-              -F application_name=${{ matrix.application }} \
-              -F translation_language=$edxLang \
-              -F source_language=en \
-              -F translations_file=@"$translations_file_path" \
-              -F source_strings_file=@"$source_strings_file_path") || curl_exit_code=$?
+            status_code=$(curl -sS --connect-timeout 10 --max-time 120 \
+              -w "%{http_code}" \
+              -o /tmp/seed_translations_response.txt \
+              -X POST "${{ vars.AI_TRANSLATIONS_SEED_TRANSLATIONS_URL }}" \
+              -F "application_name=${{ matrix.application }}" \
+              -F "translation_language=$edxLang" \
+              -F "source_language=en" \
+              -F "translations_file=@$translations_file_path" \
+              -F "source_strings_file=@$source_strings_file_path" \
+              -H "Authorization: JWT ${JWT_TOKEN}") || curl_exit_code=$?
+
 
             if [ "$curl_exit_code" -ne 0 ]; then
-              echo "Curl request failed for language $edxLang for application ${{ matrix.application }} with exit code $curl_exit_code."
+              echo "Curl request to seed translations failed for language $edxLang for application ${{ matrix.application }} with exit code $curl_exit_code."
               cat /tmp/seed_translations_response.txt
               continue
             fi
 
             if [ "$status_code" -eq 200 ]; then
-              echo "API call succeeded for language $edxLang for application ${{ matrix.application }} with status code $status_code."
+              echo "API call to seed translations succeeded for language $edxLang for application ${{ matrix.application }} with status code $status_code."
             else
-              echo "API call failed for language $edxLang for application ${{ matrix.application }} with status code $status_code."
+              echo "API call to seed translations failed for language $edxLang for application ${{ matrix.application }} with status code $status_code."
               cat /tmp/seed_translations_response.txt
             fi
           done
