feat: add some additional secrets checks

diff --git a/.github/workflows/translate-source-strings.yml b/.github/workflows/translate-source-strings.yml
--- a/.github/workflows/translate-source-strings.yml
+++ b/.github/workflows/translate-source-strings.yml
@@ -1,11 +1,8 @@
 # This workflow fetches translations for JavaScript applications by calling the AI translations
-# translate endpoint for each application anbd language code combination, using existing source string files.
+# translate endpoint for each application and language code combination, using existing source string files.
 # If successful, it commits the translated output and opens a pull request. In a select set of conditions,
 # it auto-merges the pull request.
 
-
-# This workflow seeds translations for JavaScript applications by calling the AI translations
-# seed endpoint for each application anbd language code combination, using existing source string files and translated strings file.
 name: Translate source strings
 
 on:
@@ -177,6 +174,7 @@ jobs:
       max-parallel: 1
       matrix:
         application: ${{ fromJson(needs.setup.outputs.javascript_applications) }}
+      fail-fast: false
     permissions:
       contents: write
       pull-requests: write
@@ -203,6 +201,23 @@ jobs:
             echo "Required variable AI_TRANSLATIONS_FETCH_TRANSLATIONS_URL is not set."
             missing=$((missing+1))
           fi
+
+          # Mask the client ID and secret to prevent it from being logged
+          echo "::add-mask::${{ secrets.EDX_TRANSLATIONS_STAGE_CLIENT_ID }}"
+          echo "::add-mask::${{ secrets.EDX_TRANSLATIONS_STAGE_CLIENT_SECRET }}"
+
+          # Validate that the client ID is defined
+          if [ -z "${{ secrets.EDX_TRANSLATIONS_STAGE_CLIENT_ID }}" ]; then
+            echo "Required secret EDX_TRANSLATIONS_STAGE_CLIENT_ID is not set."
+            exit 1
+          fi
+
+          # Validate that the client secret is defined
+          if [ -z "${{ secrets.EDX_TRANSLATIONS_STAGE_CLIENT_SECRET }}" ]; then
+            echo "Required secret EDX_TRANSLATIONS_STAGE_CLIENT_SECRET is not set."
+            exit 1
+          fi
+
           if [ "$missing" -ne 0 ]; then
             echo "One or more required variables are missing. Please configure them in the repository settings under Variables."
             exit 1
